### PR TITLE
Add package org-download and disable echo message from keyfreq

### PR DESCRIPTION
**Pull request by albert748**
1. org-download is image DND (Drag and drop) extension for org-mode.
for user who need manipulate images a lot make org-download very useful.
not only for DND, but links, and screenshot integration.
 refer: https://github.com/abo-abo/org-download

2. keyfreq always output "keyfreq data saved into..." and may interrupt
user input, disable this noisy message to keep silent unless failure
occured.

### CODE REVIEW

**Comment by redguardtoo** [comment]
thank. I accept your keyfreq patch. org-download is new package. Usually I need some time to evaluate new package so I won't take org-download code for now

**Comment by albert748** [comment]
It's OK for me, just try org-download, you may like it.

I've tried look around for other missing features within org-mode like full text search inside attachments.

any idea?

**Comment by redguardtoo** [comment]
I like every package developed by @abo-abo. So yes, I'm sure I will like it. I just need time for evaluation.

what do u mean attachment in org-mode?

**Comment by albert748** [comment]
directory with lots of attached files, and TAG named "ATTACH" within org file to refer to the attachment from that directory.

http://orgmode.org/manual/Attachments.html

**Comment by redguardtoo** [comment]
Interesting. Thanks for the head up.

**Pull request closed without merging**
