### PR TITLE
improve xref-ring in #746

### PR DESCRIPTION
**Pull request by karta0807913**
Hello, I tried to fix the problem in [746](https://github.com/redguardtoo/emacs.d/issues/746).
I used the `make-local-variable` keywords to spread the environment.

Best Regards.

### CODE REVIEW

**Comment by redguardtoo** [comment]
The name of `my-evil-goto-definition` might be misleading. It's actually re-implementation of `gd` in vim which goes to *local* declaration. I'm not happy that EVIL''s`gd` operator's new implementation to use xref which goes to *global* declaration.

Actually, I sent a pr to EVIL to undo that new implementation of `gd`. My pr was ignored.

So I can not use `xref`.

But you can define `your-evil-goto-definition` and bind `gd` to it.

**Comment by karta0807913** [comment]
Hello, I think EVIL's `evil-goto-definition` has the same behavior as vim's `gd`; they both go to the _global declaration_.



However, emacs's `xref` package is a storage area that allows users to store stacks into it.
For example, `lsp-mode` or `js2-mode` goes to the _local declaration_ and stores the stack into the `xref`.



So, I think you can use `xref` to store your stack.

**Comment by redguardtoo** [comment]
maybe  neovim  redefind `gd`.

Here is my vim manual,

image

On second thought, I think I can use xref to store stack with some simpler set up.

BTW, you can try my `counsel-etags` for global goto definition (need ctags).

**Comment by redguardtoo** [comment]
maybe  neovim  redefind `gd`.

Here is my vim manual,

image

On second thought, I think I can use xref to store stack with some simpler set up.

BTW, you can try my `counsel-etags` for global goto definition (need ctags).

**Pull request closed without merging**
