### PR TITLE
Update README.org

### PR DESCRIPTION
**Pull request by dalu98**

### CODE REVIEW

**Comment by redguardtoo** [comment]
Thanks

**Comment by dalu98** [comment]
I want to know what's the advantage of `workgroups2` compared to [perspective](https://github.com/nex3/perspective-el) and [persp-mode](https://github.com/Bad-ptr/persp-mode.el). 

I ask this because `doom-emacs` migrates from `workgroups2` to `persp-mode` before you started to maintain `workgroups2`..

**Comment by redguardtoo** [comment]
I started with workgroups2 and have not tried any other packages. So I can't tell the difference. My requirement is minimum for this kind of packages. So I have not spent too much time on more research.

**Comment by dalu98** [comment]
> I started with workgroups2 and have not tried any other packages. So I can't tell the difference. My requirement is minimum for this kind of packages. So I have not spent too much time on more research.

OK, thanks for your reply 😂

BTW your config is really helpful to me, I'm trying to learn your methodology from it ❤️️

**Pull request merged**
